'''
    You will only be writing code in this file and this is the only file needs modifications.
'''
import sys,csv
import pandas as pandasForSortingCSV
def get_version():
    '''
        print the version of python that you are using.
    '''
    "*** WRITE YOUR CODE HERE ***"
    print("当前python版本")
    print(sys.version)
    print("Version info")
    print(sys.version_info)
    

def alternative_sum(start,n):
    '''
        modify the function to return a list with generated by an alternative sum sequence explained in the assignment handout
    '''
    "*** WRITE YOUR CODE HERE ***"
    arr=[]
    if (start<=0) or (n<5) or (n>20):
        print(arr)
        return
    arr.append(start)
    arr.append(start*2)
    arr.append(start*4)
    for i in range(4,n+1):
        elment=arr[i-2]+arr[i-4]
        arr.append(elment)
    print(arr)
    return arr
    
def order_scores():
    '''
        read the files scores.csv in the data directory and return the list of names sorted in ascending order of the scores.
    '''
    "*** WRITE YOUR CODE HERE ***"

    csvData = pandasForSortingCSV.read_csv("/Users/apple/450/hw1-zhuxin696/data/scores.csv")

    csvData.sort_values(["scores"],
                        axis=0,
                        ascending=[True],
                        inplace=True)
    res=csvData['name'].tolist()
    print(res)
    return res
