'''
    You will only be writing code in this file and this is the only file needs modifications.
'''

def get_version():
    '''
        print the version of python that you are using.
    '''
    "*** WRITE YOUR CODE HERE ***"


def alternative_sum():
    '''
        modify the function to return a list with generated by an alternative sum sequence explained in the assignment handout
    '''
    "*** WRITE YOUR CODE HERE ***"


def order_scores():
    '''
        read the files scores.csv in the data directory and return the list of names sorted in ascending order of the scores.
    '''
    "*** WRITE YOUR CODE HERE ***"

